package com.paysi.ledger.domain;
public enum TransactionType { SALE, GUARANTEE_RELEASE, RELEASE, RESERVE_RELEASE, REFUND, CHARGEBACK, CHARGEBACK_REVERSAL, PAYOUT, PAYOUT_REVERSAL, PLATFORM_FEE, DEBT_WRITEOFF, ADJUSTMENT, ANTICIPATION }
