spring:
  flyway:
    clean-disabled: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: INFO
    com.paysi: INFO

paysi:
  mfa:
    encryption-key: ${MFA_ENCRYPTION_KEY_BASE64}
